/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: CdR (https://sketchfab.com/CdRibin)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/20-sides-icosahedron-dice-078f9ccad62a481f86b3a42d040acbe5
Title: 20 sides icosahedron Dice
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei/native'
import { GLTF } from 'three-stdlib'
import { Asset } from 'expo-asset';


type GLTFResult = GLTF & {
  nodes: {
    Object_2: THREE.Mesh
  }
  materials: {
    ['Scene_-_Root']: THREE.MeshStandardMaterial
  }
}

export function D20(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(Asset.fromModule(require("../assets/models/20_sides_icosahedron_dice.glb")).uri) as GLTFResult;
  return (
    <group {...props} dispose={null} position={[0, 0, 0]}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_2.geometry}
        material={materials['Scene_-_Root']}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.05}
      />
    </group>
  )
}

useGLTF.preload('/20_sides_icosahedron_dice.glb')


